.PHONY: generate

generate:
	stringer -type ColumnFlag -output column_flag.string.go column_flag.go
	stringer -type Prefix -output prefix.string.go prefix.go
	stringer -type State -output state_flag.string.go state_flag.go
