.PHONY: generate

generate:
	stringer -type ColumnFlag -output column_flag.string.go column_flag.go
	stringer -type Prefix -output prefix.string.go prefix.go
	stringer -type TypeFamily -output type_family.string.go type_family.go